#!/bin/bash

source ./decorate.sh

title -d 1 "Destroying pfcon containerized development environment" "from ./docker-compose.yml"
windowBottom

title -d 1 "Stopping services..."
    docker-compose stop
windowBottom

title -d 1 "Removing all containers..."
    docker-compose rm -vf 
windowBottom

title -d 1 "Removing any orphans..."
    a_VOLS=(
        "pfcon_swift_storage"
        "pman"
        "pfioh"
        "/pfcon"
    )
    a_PVOLS=()
    for vol in ${a_VOLS[@]}; do
        SCANTXT=$(printf "Scanning for '%s'... " "$vol")
        printf "%50s" "$SCANTXT"
        DOCKERPS=$(docker ps -a | grep -v CONTAINER | grep $vol)
        DOCKERVOLNAME=$(echo $DOCKERPS | awk '{print $2}')
        DOCKERID=$(echo $DOCKERPS | awk '{print $1}')
        if (( ${#DOCKERVOLNAME} )); then
            printf "${Yellow}[ %s ]${NC}\n" "$DOCKERID:$DOCKERVOLNAME"
        else
            printf "${Green}[ Not orphaned. ]${NC}\n"
        fi
        a_PVOLS+=($DOCKERID)
    done
    printf "\n"
    for VOL in ${a_PVOLS[@]} ; do 
        printf "${Cyan}Removing ${Yellow}[ $VOL ]${Cyan}${NC}\n"
        docker stop $VOL >/dev/null && docker rm -vf $VOL > /dev/null
    done
windowBottom

title -d 1 "Destroying persistent volumes..."
    basedir=`pwd | xargs basename | awk '{print tolower($0)}'`
    a_VOLS=(
        "pfcon_swift_storage"
    )
    a_PVOLS=()
    for vol in ${a_VOLS[@]}; do
        SCANTXT=$(printf "Scanning for '%s'... " "$vol")
        printf "%50s" "$SCANTXT"
        DOCKERVOLNAME=$(docker volume ls | grep -v DRIVER | awk {'print $2'} | grep $vol)
        if (( ${#DOCKERVOLNAME} )); then
            printf "${Green}[ %s ]${NC}\n" "$DOCKERVOLNAME"
        else
            printf "${Red}[ Not found. ]${NC}\n"
        fi
        a_PVOLS+=($DOCKERVOLNAME)
    done
    printf "\n"
    for VOL in ${a_PVOLS[@]} ; do 
        printf "${Cyan}Do you want to remove persistent volume ${Green}[ $VOL ]${Cyan}?${NC}"
        read -p  " [y/n] " -n 1 -r
        echo
        if [[ $REPLY =~ ^[Yy]$ ]] ; then
            docker volume rm $VOL
        fi
    done
windowBottom

title -d 1 "Stopping swarm cluster..."
    docker swarm leave --force
windowBottom
