kind: Kustomization

namespace: ${NAMESPACE}

configMapGenerator:
- name: pfcon-config
  env: secrets/.pfcon.env
- name: pman-config
  env: secrets/.pman.env

resources:
- resources/pfcon.yaml
- resources/pman.yaml

vars:
- name: PMAN_SERVICE_NAME
  objref:
    kind: Service
    name: pman
    apiVersion: v1
