apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: storebase
spec:
  accessModes:
  - ReadWriteMany
  storageClassName: ""
  resources:
    requests:
      storage: 10Gi
  selector:
    matchLabels:
      volume: storebase
