apiVersion: v1
kind: Service
metadata:
  name: pfcon
  labels:
    app: pfcon
    env: development
spec:
  type: NodePort
  selector:
    app: pfcon
    env: development
  ports:
    - port: 30006
      targetPort: 5005
      nodePort: 30006

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: pfcon
  labels:
    app: pfcon
    env: development
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pfcon
      env: development
  template:
    metadata:
      name: pfcon
      labels:
        app: pfcon
        env: development
    spec:
      containers:
        - image: localhost:5000/fnndsc/pfcon:dev
          name: pfcon
          stdin: true
          tty: true
          ports:
            - containerPort: 5005
          env:
            - name: APPLICATION_MODE
              value: development
            - name: PFCON_INNETWORK
              value: true
            - name: STORAGE_ENV
              value: fslink
            - name: COMPUTE_VOLUME_TYPE
            - value: host
            - name: STOREBASE
              value: ${STOREBASE}
            - name: CONTAINER_ENV
              value: kubernetes
          command: ["python"]
          args: ["-m", "pfcon"]
          volumeMounts:
            - mountPath: "/var/local/storeBase"
              name: "storebase"
            - mountPath: "/app/pfcon"
              name: "pfcon-source"
            - mountPath: "/app/tests"
              name: "pfcon-tests"
      volumes:
        - name: "storebase"
          hostPath:
            path: ${STOREBASE}
        - name: "pfcon-source"
          hostPath:
            path: ${SOURCEDIR}/pfcon
        - name: "pfcon-tests"
          hostPath:
            path: ${SOURCEDIR}/tests
