apiVersion: v1
kind: ServiceAccount
metadata:
  name: pfcon
  labels:
    app: pfcon
    env: development

---

apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: pfcon
  labels:
    app: pfcon
    env: development
rules:
  - apiGroups: ["batch"]
    resources: ["jobs"]
    verbs: ["create", "get", "list", "watch", "delete"]
  - apiGroups: [""]
    resources: ["pods"]
    verbs: ["get", "list", "watch"]
  - apiGroups: [""]
    resources: ["pods/log"]
    verbs: ["get"]
  - apiGroups: [""]
    resources: ["pods/status"]
    verbs: ["get"]

---

apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: pfcon
  labels:
    app: pfcon
    env: development
subjects:
  - kind: ServiceAccount
    name: pfcon
    namespace: default
roleRef:
  kind: Role
  name: pfcon
  apiGroup: rbac.authorization.k8s.io

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: storebase-pvc
  labels:
    app: pfcon
    env: development
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: hostpath
  resources:
    requests:
      storage: 2Gi

---

apiVersion: v1
kind: Service
metadata:
  name: pfcon
  labels:
    app: pfcon
    env: development
spec:
  type: NodePort
  selector:
    app: pfcon
    env: development
  ports:
    - port: 30006
      targetPort: 5005
      nodePort: 30006

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: pfcon
  labels:
    app: pfcon
    env: development
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pfcon
      env: development
  template:
    metadata:
      name: pfcon
      labels:
        app: pfcon
        env: development
    spec:
      serviceAccountName: pfcon
      initContainers:
        - name: init-s3
          image: busybox:1.32
          command: ["sh", "-c", "until wget --spider -S -T 2 http://s3-service:9000/minio/health/live 2>&1 | grep '200 OK'; do echo waiting for S3 storage; sleep 2; done"]
      containers:
        - image: localhost:5000/fnndsc/pfcon:dev
          name: pfcon
          stdin: true
          tty: true
          ports:
            - containerPort: 5005
          env:
            - name: APPLICATION_MODE
              value: development
            - name: PFCON_INNETWORK
              value: "true"
            - name: STORAGE_ENV
              value: s3
            - name: COMPUTE_VOLUME_TYPE
              value: kubernetes_pvc
            - name: VOLUME_NAME
              value: storebase-pvc
            - name: STOREBASE_MOUNT
              value: /var/local/storeBase
            - name: CONTAINER_ENV
              value: kubernetes
            - name: PFCON_OP_IMAGE
              value: ghcr.io/fnndsc/pfconopjob-s3
            - name: S3_ENDPOINT_URL
              value: http://s3-service:9000
          command: ["pixi"]
          args: ["run", "python", "-m", "pfcon"]
          volumeMounts:
            - mountPath: "/var/local/storeBase"
              name: "storebase"
            - mountPath: "/app/pfcon"
              name: "pfcon-source"
            - mountPath: "/app/tests"
              name: "pfcon-tests"
      volumes:
        - name: "storebase"
          persistentVolumeClaim:
            claimName: storebase-pvc
        - name: "pfcon-source"
          hostPath:
            path: ${SOURCEDIR}/pfcon
        - name: "pfcon-tests"
          hostPath:
            path: ${SOURCEDIR}/tests

---

apiVersion: v1
kind: Service
metadata:
  name: s3-service
  labels:
    app: s3
    env: production
spec:
  type: NodePort
  selector:
    app: s3
    env: production
  ports:
    - name: api
      port: 9000
      targetPort: 9000
      nodePort: 30090
    - name: console
      port: 9001
      targetPort: 9001
      nodePort: 30091

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: s3
  labels:
    app: s3
    env: production
spec:
  replicas: 1  # stateful service, so only a single replica must be used
  selector:
    matchLabels:
      app: s3
      env: production
  template:
    metadata:
      name: s3
      labels:
        app: s3
        env: production
    spec:
      containers:
        - name: s3
          image: docker.io/minio/minio:latest
          args: ["server", "/data", "--console-address", ":9001"]
          ports:
            - containerPort: 9000
            - containerPort: 9001
          env:
            - name: MINIO_ROOT_USER
              value: minioadmin
            - name: MINIO_ROOT_PASSWORD
              value: minioadmin
          volumeMounts:
            - name: s3db
              mountPath: "/data"
      volumes:
        - name: s3db
          hostPath:
            path: ${SOURCEDIR}/s3_storage
