apiVersion: v1
kind: Service
metadata:
  name: pfcon
  labels:
    app: pfcon
    env: development
spec:
  type: NodePort
  selector:
    app: pfcon
    env: development
  ports:
    - port: 30006
      targetPort: 5005
      nodePort: 30006

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: pfcon
  labels:
    app: pfcon
    env: development
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pfcon
      env: development
  template:
    metadata:
      name: pfcon
      labels:
        app: pfcon
        env: development
    spec:
      initContainers:
        - name: init-swift
          image: busybox:1.32
          command: [ "sh", "-c", "until wget --spider -S -T 2 http://swift:8080/info 2>&1 | grep '200 OK'; do echo waiting for Swift storage; sleep2; done" ]
      containers:
        - image: fnndsc/pfcon:dev
          name: pfcon
          stdin: true
          tty: true
          ports:
            - containerPort: 5005
          env:
            - name: APPLICATION_MODE
              value: development
            - name: PFCON_INNETWORK
              value: true
            - name: STORAGE_ENV
              value: swift
            - name: COMPUTE_VOLUME_TYPE
            - value: host
            - name: STOREBASE
              value: ${STOREBASE}
            - name: CONTAINER_ENV
              value: kubernetes
          command: ["python"]
          args: ["-m", "pfcon"]
          volumeMounts:
            - mountPath: "/var/local/storeBase"
              name: "storebase"
            - mountPath: "/app/pfcon"
              name: "pfcon-source"
            - mountPath: "/app/tests"
              name: "pfcon-tests"
      volumes:
        - name: "storebase"
          hostPath:
            path: ${STOREBASE}
        - name: "pfcon-source"
          hostPath:
            path: ${SOURCEDIR}/pfcon
        - name: "pfcon-tests"
          hostPath:
            path: ${SOURCEDIR}/tests

---

apiVersion: v1
kind: Service
metadata:
  name: swift
  labels:
    app: swift
    env: production
spec:
  type: NodePort
  selector:
    app: swift
    env: production
  ports:
    - port: 8080
      targetPort: 8080
      nodePort: 30080

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: swift
  labels:
    app: swift
    env: production
spec:
  replicas: 1  # stateful service, so only a single replica must be used
  selector:
    matchLabels:
      app: swift
      env: production
  template:
    metadata:
      name: swift
      labels:
        app: swift
        env: production
    spec:
      containers:
        - name: swift
          image: fnndsc/docker-swift-onlyone
          ports:
            - containerPort: 8080
          env:
            - name: SWIFT_USERNAME
              value: chris:chris1234
            - name: SWIFT_KEY
              value: testing
          volumeMounts:
            - name: swiftdb
              mountPath: "/srv"
      volumes:
        - name: swiftdb
          hostPath:
            path: ${SOURCEDIR}/swift_storage
