# run pfcon unit tests (nosetests) and CUBE integration tests.
# If all tests pass, build a multi-arch image and push to DockerHub.

name: CI

on:
  push:
    branches: [ master ]
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+*'
  pull_request:
    branches: [ master ]

jobs:
  test-pfcon:
    name: tests (pfcon)
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
      - name: Start Docker Swarm
        run: docker swarm init --advertise-addr 127.0.0.1
      - name: Build and run tests
        run: ./make.sh -i
      - name: Tear down
        run: |
          ./unmake.sh
          sudo rm -fr ./CHRIS_REMOTE_FS
          docker swarm leave --force
  test-cube:
    name: tests (CUBE)
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
      - run: docker build -t localhost/fnndsc/pfcon .
      - uses: FNNDSC/ChRIS_ultron_backEnd@master
        env:
          PFCON_IMAGE: localhost/fnndsc/pfcon

  build:
    needs: [test-pfcon, test-cube]
    runs-on: ubuntu-24.04
    env:
      PIXI_COLOR: always
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Install micromamba
      uses: mamba-org/setup-micromamba@v2
      with:
        cache-downloads: true
    - name: Install pixi
      uses: prefix-dev/setup-pixi@v0.8.1
      with:
        pixi-version: v0.38.0
        run-install: false
    - name: Set version
      if: startsWith(github.ref, 'refs/tags/v')
      run: |
        ref_name='${{ github.ref_name }}'
        version_number="${ref_name:1}"
        pixi project version set "$version_number"
    - name: Docker meta
      id: meta
      uses: docker/metadata-action@v5
      with:
        images: |
          docker.io/fnndsc/pfcon
          ghcr.io/fnndsc/pfcon
        tags: |
          type=ref,event=branch
          type=ref,event=pr
          type=pep440,pattern={{version}}
          type=pep440,pattern={{major}}.{{minor}}
          type=raw,value=latest,enable={{is_default_branch}}

      # pixi and micromamba don't have ppc64le images available, so to build
      # images for ppc64le, we create conda environments using micromamba
      # which are then copied into the container images. This also happens
      # to be more efficient than running a package manager during docker
      # build using QEMU.
    - name: Export conda-explicit-spec
      run: pixi project export conda-explicit-spec --frozen --ignore-pypi-errors conda-specs
    - name: Create env for linux/amd64
      run: micromamba create --platform linux-64      --relocate-prefix /opt/conda-env -f conda-specs/prod_linux-64_conda_spec.txt -p ./envs/linux/amd64
    - name: Create env for linux/arm64
      run: micromamba create --platform linux-aarch64 --relocate-prefix /opt/conda-env -f conda-specs/prod_linux-aarch64_conda_spec.txt -p ./envs/linux/arm64
    - name: Create env for linux/ppc64le
      run: micromamba create --platform linux-ppc64le --relocate-prefix /opt/conda-env -f conda-specs/prod_linux-ppc64le_conda_spec.txt -p ./envs/linux/ppc64le
    - name: Build wheel
      run: pixi run build

    - uses: docker/setup-qemu-action@v3
    - uses: docker/setup-buildx-action@v3
    - name: Login to DockerHub
      id: login-dockerhub
      if: github.event_name == 'push'
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_PASSWORD }}
    - name: Login to GitHub Container Registry
      id: login-ghcr
      if: github.event_name == 'push'
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.repository_owner }}
        password: ${{ secrets.GITHUB_TOKEN }}
    - name: Build and push
      uses: docker/build-push-action@v6
      with:
        push: ${{ steps.login-dockerhub.outcome == 'success' && steps.login-ghcr.outcome == 'success' }}
        context: .
        file: ./prod.Dockerfile
        platforms: linux/amd64,linux/arm64,linux/ppc64le
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}
        cache-from: type=gha
        cache-to: type=gha,mode=max
